[2025-03-17T10:47:39.191+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:47:39.193+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:47:39.195+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:47:39.194+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:47:39.211+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:47:39.210+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:47:39.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:47:39.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.056 seconds
[2025-03-17T10:48:09.730+0000] {processor.py:161} INFO - Started process (PID=173) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:09.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:48:09.733+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:48:09.732+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:09.746+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:48:09.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:48:09.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:09.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.045 seconds
[2025-03-17T10:48:40.057+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:40.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:48:40.060+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:48:40.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:40.076+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:48:40.073+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:48:40.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:48:40.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.077 seconds
[2025-03-17T10:49:10.688+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:10.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:49:10.690+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:49:10.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:10.700+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:49:10.699+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:49:10.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:10.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.044 seconds
[2025-03-17T10:49:40.909+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:40.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:49:40.912+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:49:40.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:40.926+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:49:40.925+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:49:40.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:49:40.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.050 seconds
[2025-03-17T10:50:12.289+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:12.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:50:12.291+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:50:12.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:12.301+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:50:12.300+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:50:12.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:12.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.040 seconds
[2025-03-17T10:50:43.867+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:43.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:50:43.869+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:50:43.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:43.878+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:50:43.877+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:50:43.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:50:43.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.041 seconds
[2025-03-17T10:51:14.929+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:14.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:51:14.930+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:51:14.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:14.941+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:51:14.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:51:14.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:14.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.033 seconds
[2025-03-17T10:51:45.933+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:45.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:51:45.936+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:51:45.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:45.946+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:51:45.945+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:51:45.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:51:45.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.040 seconds
[2025-03-17T10:52:16.990+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:16.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:52:16.992+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:52:16.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:17.002+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:52:17.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:52:17.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:17.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.035 seconds
[2025-03-17T10:52:47.919+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:47.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:52:47.920+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:52:47.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:47.929+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:52:47.929+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:52:47.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:52:47.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.031 seconds
[2025-03-17T10:53:19.082+0000] {processor.py:161} INFO - Started process (PID=418) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:19.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:53:19.084+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:19.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:19.097+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:19.095+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 26
    ВАШ КОД
           ^
SyntaxError: invalid syntax
[2025-03-17T10:53:19.098+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:19.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.043 seconds
[2025-03-17T10:53:20.434+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:20.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:53:20.436+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:20.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:21.038+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:21.126+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:21.125+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:53:21.140+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:21.140+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:53:21.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.747 seconds
[2025-03-17T10:53:51.705+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:51.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:53:51.708+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:51.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:52.724+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:53:52.747+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:52.746+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:53:52.768+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:53:52.768+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:53:52.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 1.102 seconds
[2025-03-17T10:54:23.177+0000] {processor.py:161} INFO - Started process (PID=469) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:23.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:54:23.179+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:23.179+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:23.857+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:23.862+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:23.861+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:54:23.889+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:23.889+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:54:23.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.759 seconds
[2025-03-17T10:54:54.225+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:54.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:54:54.227+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:54.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:54.697+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:54:54.757+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:54.757+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:54:54.769+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:54:54.769+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:54:54.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.565 seconds
[2025-03-17T10:55:25.065+0000] {processor.py:161} INFO - Started process (PID=519) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:25.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:55:25.067+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:25.067+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:25.587+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:25.596+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:25.596+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:55:25.610+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:25.610+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:55:25.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.565 seconds
[2025-03-17T10:55:55.999+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:55.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:55:56.000+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:56.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:56.553+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:55:56.557+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:56.556+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:55:56.571+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:55:56.571+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:55:56.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.550 seconds
[2025-03-17T10:56:27.052+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:27.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:56:27.054+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:27.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:27.597+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:27.663+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:27.662+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:56:27.683+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:27.683+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:56:27.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.655 seconds
[2025-03-17T10:56:58.033+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:58.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:56:58.036+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:58.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:58.604+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:56:58.621+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:58.620+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:56:58.653+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:56:58.653+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:56:58.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.654 seconds
[2025-03-17T10:57:29.142+0000] {processor.py:161} INFO - Started process (PID=619) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:57:29.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:57:29.144+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:57:29.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:57:29.692+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:57:29.695+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:57:29.695+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:57:29.709+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:57:29.709+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:57:29.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.597 seconds
[2025-03-17T10:58:00.251+0000] {processor.py:161} INFO - Started process (PID=644) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:00.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:58:00.254+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:00.253+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:00.944+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:01.038+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:01.037+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:58:01.053+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:01.053+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:58:01.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.836 seconds
[2025-03-17T10:58:31.791+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:31.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:58:31.793+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:31.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:32.373+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:58:32.386+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:32.385+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:58:32.405+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:58:32.405+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:58:32.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.647 seconds
[2025-03-17T10:59:03.325+0000] {processor.py:161} INFO - Started process (PID=694) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:03.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:59:03.327+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:03.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:03.810+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:03.814+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:03.813+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:59:03.829+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:03.829+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:59:03.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.529 seconds
[2025-03-17T10:59:34.718+0000] {processor.py:161} INFO - Started process (PID=719) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:34.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T10:59:34.721+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:34.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:35.769+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T10:59:35.878+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:35.877+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T10:59:35.897+0000] {logging_mixin.py:188} INFO - [2025-03-17T10:59:35.897+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T10:59:35.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 1.226 seconds
[2025-03-17T11:00:06.484+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:06.485+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:00:06.486+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:06.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:07.066+0000] {processor.py:840} INFO - DAG(s) '6_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:07.085+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:07.085+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:00:07.113+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:07.113+0000] {dag.py:3823} INFO - Setting next_dagrun for 6_house_assignment to None, run_after=None
[2025-03-17T11:00:07.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.663 seconds
[2025-03-17T11:00:25.242+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:25.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:00:25.246+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:25.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:25.938+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:25.932+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:00:25.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:25.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.722 seconds
[2025-03-17T11:00:32.051+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:32.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:00:32.053+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:32.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:32.764+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:00:32.760+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:00:32.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:00:32.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.734 seconds
[2025-03-17T11:01:03.619+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:03.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:01:03.621+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:03.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:04.284+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:04.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:01:04.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:04.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.686 seconds
[2025-03-17T11:01:11.612+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:11.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:01:11.614+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:11.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:12.163+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:12.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:01:12.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:12.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.573 seconds
[2025-03-17T11:01:27.496+0000] {processor.py:161} INFO - Started process (PID=811) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:27.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:01:27.498+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:27.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:28.264+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:28.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:01:28.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:28.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.797 seconds
[2025-03-17T11:01:59.297+0000] {processor.py:161} INFO - Started process (PID=836) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:59.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:01:59.300+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:59.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:59.952+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:01:59.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:01:59.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:01:59.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.679 seconds
[2025-03-17T11:02:06.183+0000] {processor.py:161} INFO - Started process (PID=843) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:06.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:02:06.186+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:06.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:06.717+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:06.713+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:02:06.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:06.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.554 seconds
[2025-03-17T11:02:09.299+0000] {processor.py:161} INFO - Started process (PID=846) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:09.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:02:09.301+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:09.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:09.827+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:09.823+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:02:09.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:09.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.546 seconds
[2025-03-17T11:02:40.109+0000] {processor.py:161} INFO - Started process (PID=871) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:40.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:02:40.111+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:40.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:40.857+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:02:40.851+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:02:40.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:02:40.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.776 seconds
[2025-03-17T11:03:10.951+0000] {processor.py:161} INFO - Started process (PID=896) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:10.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:03:10.954+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:03:10.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:11.553+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:03:11.548+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:03:11.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:11.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.629 seconds
[2025-03-17T11:03:42.269+0000] {processor.py:161} INFO - Started process (PID=921) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:42.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:03:42.271+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:03:42.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:42.942+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:03:42.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:03:42.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:03:42.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.694 seconds
[2025-03-17T11:04:13.106+0000] {processor.py:161} INFO - Started process (PID=946) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:13.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:04:13.108+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:13.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:13.798+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:13.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:04:13.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:13.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.713 seconds
[2025-03-17T11:04:44.591+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:44.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:04:44.593+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:44.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:45.125+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:45.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:04:45.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:45.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.551 seconds
[2025-03-17T11:04:47.254+0000] {processor.py:161} INFO - Started process (PID=974) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:47.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:04:47.257+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:47.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:47.975+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:04:47.972+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:04:47.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:04:47.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.741 seconds
[2025-03-17T11:05:18.578+0000] {processor.py:161} INFO - Started process (PID=999) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:18.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:05:18.580+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:18.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:19.088+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:19.084+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 106, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:05:19.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:19.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.535 seconds
[2025-03-17T11:05:27.555+0000] {processor.py:161} INFO - Started process (PID=1008) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:27.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:05:27.557+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:27.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:28.201+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:28.198+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 105, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:05:28.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:28.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.567 seconds
[2025-03-17T11:05:49.639+0000] {processor.py:161} INFO - Started process (PID=1026) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:49.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:05:49.641+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:49.641+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:50.163+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:05:50.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 102, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:05:50.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:05:50.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.544 seconds
[2025-03-17T11:06:21.291+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:21.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:06:21.295+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:06:21.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:22.481+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:06:22.477+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 102, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:06:22.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:22.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 1.214 seconds
[2025-03-17T11:06:52.765+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:52.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:06:52.767+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:06:52.767+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:53.485+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:06:53.479+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/7_1_house_assignment.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/7_1_house_assignment.py", line 102, in <module>
    create_currency_data = ClickHouseOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow_clickhouse_plugin/operators/clickhouse.py", line 49, in __init__
    super().__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 811, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/task_group.py", line 231, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'create_table' has already been added to the DAG
[2025-03-17T11:06:53.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:53.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.743 seconds
[2025-03-17T11:06:59.755+0000] {processor.py:161} INFO - Started process (PID=1083) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:06:59.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:06:59.757+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:06:59.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:00.329+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:00.412+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.411+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:7_house_assignment
[2025-03-17T11:07:00.422+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.422+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:7_house_assignment
[2025-03-17T11:07:00.430+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.429+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:7_house_assignment
[2025-03-17T11:07:00.431+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.430+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:07:00.440+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.439+0000] {dag.py:3058} INFO - Creating ORM DAG for 7_house_assignment
[2025-03-17T11:07:00.452+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:00.452+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:07:00.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.725 seconds
[2025-03-17T11:07:03.512+0000] {processor.py:161} INFO - Started process (PID=1087) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:03.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:07:03.519+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:03.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:04.349+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:04.353+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:04.353+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:07:04.370+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:04.370+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:07:04.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.897 seconds
[2025-03-17T11:07:39.271+0000] {processor.py:161} INFO - Started process (PID=1211) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:39.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:07:39.273+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:39.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:39.949+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:07:39.962+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:07:39.962+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:07:40.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.736 seconds
[2025-03-17T11:08:10.307+0000] {processor.py:161} INFO - Started process (PID=1236) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:08:10.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:08:10.309+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:08:10.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:08:10.788+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:08:10.799+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:08:10.799+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:08:10.813+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:08:10.813+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-02 00:00:00+00:00, run_after=2024-01-03 00:00:00+00:00
[2025-03-17T11:08:10.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.527 seconds
[2025-03-17T11:09:13.286+0000] {processor.py:161} INFO - Started process (PID=1510) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:13.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:09:13.289+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:13.288+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:13.959+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:14.049+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:14.049+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:09:14.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.814 seconds
[2025-03-17T11:09:51.174+0000] {processor.py:161} INFO - Started process (PID=1668) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:51.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:09:51.176+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:51.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:51.710+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:09:51.782+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:51.781+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:09:51.790+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:51.789+0000] {dag.py:3058} INFO - Creating ORM DAG for 7_house_assignment
[2025-03-17T11:09:51.796+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:09:51.796+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:09:51.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.643 seconds
[2025-03-17T11:10:22.151+0000] {processor.py:161} INFO - Started process (PID=1693) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:22.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:10:22.153+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:22.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:22.715+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:22.726+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:22.725+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:10:22.741+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:22.740+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:10:22.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.615 seconds
[2025-03-17T11:10:52.994+0000] {processor.py:161} INFO - Started process (PID=1718) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:52.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:10:52.996+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:52.996+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:53.571+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:10:53.584+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:53.583+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:10:53.599+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:10:53.599+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:10:53.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.629 seconds
[2025-03-17T11:11:24.448+0000] {processor.py:161} INFO - Started process (PID=1743) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:24.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:11:24.450+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:24.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:25.000+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:25.011+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:25.010+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:11:25.026+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:25.025+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:11:25.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.602 seconds
[2025-03-17T11:11:55.957+0000] {processor.py:161} INFO - Started process (PID=1768) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:55.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:11:55.959+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:55.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:56.499+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:11:56.517+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:56.516+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:11:56.543+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:11:56.543+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:11:56.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.633 seconds
[2025-03-17T11:12:26.757+0000] {processor.py:161} INFO - Started process (PID=1793) to work on /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:12:26.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/7_1_house_assignment.py for tasks to queue
[2025-03-17T11:12:26.760+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:12:26.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:12:27.279+0000] {processor.py:840} INFO - DAG(s) '7_house_assignment' retrieved from /opt/airflow/dags/7_1_house_assignment.py
[2025-03-17T11:12:27.288+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:12:27.288+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-03-17T11:12:27.301+0000] {logging_mixin.py:188} INFO - [2025-03-17T11:12:27.300+0000] {dag.py:3823} INFO - Setting next_dagrun for 7_house_assignment to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2025-03-17T11:12:27.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/7_1_house_assignment.py took 0.570 seconds
